jobs:
- name: damian_demo_build_job
  plan:
  - get: damian_demo_dockerfile
    trigger: true
  - put: damian_demo_build_image
    params: {build: damian_demo_dockerfile}
resources:
- name: damian_demo_dockerfile
  type: git
  source:
   uri: https://github.com/eneasz/concourse-demo.git
   branch: master
   paths: [Dockerfile]
- name: damian_demo_build_image
  type: docker-image
  source:
   repository: eneasz/miniblog
   email: ((docker_mail))
   username: ((docker_user))
   password: ((docker_pass))
